CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
id Int (50) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR (100) NOT NULL,
devoured BOOLEAN NOT NULL Default 0,
date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);

