DROP DATABASE IF Exists b53onvhwftf587py;

CREATE DATABASE b53onvhwftf587py;

USE b53onvhwftf587py;

CREATE TABLE burgers (
id Int (50) AUTO_INCREMENT NOT NULL,
burger_name VARCHAR (100) NOT NULL,
devoured BOOLEAN DEFAULT false,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
PRIMARY KEY (id)
);